name: kafka-cluster

services:
  kafka:
    image: confluentinc/cp-kafka:8.0.0
    networks:
      - kraft-net
    ports:
      - 9092:9092
      - 29092:29092
    hostname: kafka1
    container_name: kafka1
    environment:
      # KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      #      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_MESSAGE_MAX_BYTES: 5242880
      KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
      KAFKA_FETCH_MAX_BYTES: 5242880
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29092,2@kafka2:29093"
      KAFKA_CLUSTER_ID: ${CLUSTER_ID}
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

      # Listeners
      KAFKA_LISTENERS: CONTROLLER://kafka1:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: CONTROLLER://kafka1:29092,EXTERNAL://${EXTERNAL_HOST}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas.conf
      # ACLs
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin;User:broker

      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./security/admin-client.properties:/etc/kafka/admin-client.properties
      - kafka1-data:/var/lib/kafka/data
      - ./security/jaas.conf:/etc/kafka/jaas.conf
    restart: always

  kafka2:
    image: confluentinc/cp-kafka:8.0.0
    networks:
      - kraft-net
    ports:
      - 9093:9093
      - 29093:29093
    hostname: kafka2
    container_name: kafka2
    environment:
      # KRaft
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      #      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_MESSAGE_MAX_BYTES: 5242880
      KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
      KAFKA_FETCH_MAX_BYTES: 5242880
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29092,2@kafka2:29093"
      KAFKA_CLUSTER_ID: ${CLUSTER_ID}
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

      # Listeners
      KAFKA_LISTENERS: CONTROLLER://kafka2:29093,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: CONTROLLER://kafka2:29093,EXTERNAL://${EXTERNAL_HOST}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas.conf


      # ACLs
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin;User:broker


      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./security/admin-client.properties:/etc/kafka/admin-client.properties
      - kafka2-data:/var/lib/kafka/data
      - ./security/jaas.conf:/etc/kafka/jaas.conf
    restart: always

networks:
  kraft-net:
    name: kafka-kraft-network

volumes:
  kafka1-data:
  kafka2-data: