name: kafka-cluster

services:
  kafka:
    image: confluentinc/cp-kafka:8.0.0
    networks:
      - kraft-net
    ports:
      - 9092:9092
      - 29092:29092
      - 19092:19092
    hostname: kafka1
    container_name: kafka1
    environment:
      # KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      #      KAFKA_MESSAGE_MAX_BYTES: 5242880
      #      KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
      #      KAFKA_FETCH_MAX_BYTES: 5242880
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29092,2@kafka2:29093,3@kafka3:29094"
      KAFKA_CLUSTER_ID: ${CLUSTER_ID}
      CLUSTER_ID: ${CLUSTER_ID}

      # Listeners
      KAFKA_LISTENERS: CONTROLLER://kafka1:29092,EXTERNAL://0.0.0.0:9092,BROKER://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: CONTROLLER://kafka1:29092,EXTERNAL://${EXTERNAL_HOST}:9092, BROKER://kafka1:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,BROKER:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas.conf

      # ACLs
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin;User:broker

      # Replication
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3 #по количеству нод
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3 #по количеству нод
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./security/admin-client.properties:/etc/kafka/admin-client.properties
      - kafka1-data:/var/lib/kafka/data
      - ./security/jaas.conf:/etc/kafka/jaas.conf
    restart: always

  kafka2:
    image: confluentinc/cp-kafka:8.0.0
    networks:
      - kraft-net
    ports:
      - 9093:9093
      - 29093:29093
      - 19093:19093
    hostname: kafka2
    container_name: kafka2
    environment:
      # KRaft
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      #      KAFKA_MESSAGE_MAX_BYTES: 5242880
      #      KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
      #      KAFKA_FETCH_MAX_BYTES: 5242880
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29092,2@kafka2:29093,3@kafka3:29094"
      KAFKA_CLUSTER_ID: ${CLUSTER_ID}
      CLUSTER_ID: ${CLUSTER_ID}

      # Listeners
      KAFKA_LISTENERS: CONTROLLER://kafka2:29093,EXTERNAL://0.0.0.0:9093,BROKER://0.0.0.0:19093
      KAFKA_ADVERTISED_LISTENERS: CONTROLLER://kafka2:29093,EXTERNAL://${EXTERNAL_HOST}:9093, BROKER://kafka2:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,BROKER:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas.conf

      # ACLs
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin;User:broker

      # Replication для 2 брокеров
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3 #по количеству нод
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3 #по количеству нод
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./security/admin-client.properties:/etc/kafka/admin-client.properties
      - kafka2-data:/var/lib/kafka/data
      - ./security/jaas.conf:/etc/kafka/jaas.conf
    restart: always

  kafka3:
    image: confluentinc/cp-kafka:8.0.0
    networks:
      - kraft-net
    ports:
      - 9094:9094
      - 29094:29094
      - 19094:19094
    hostname: kafka3
    container_name: kafka3
    environment:
      # KRaft
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      #      KAFKA_MESSAGE_MAX_BYTES: 5242880
      #      KAFKA_REPLICA_FETCH_MAX_BYTES: 5242880
      #      KAFKA_FETCH_MAX_BYTES: 5242880
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:29092,2@kafka2:29093,3@kafka3:29094"
      KAFKA_CLUSTER_ID: ${CLUSTER_ID}
      CLUSTER_ID: ${CLUSTER_ID}

      # Listeners
      KAFKA_LISTENERS: CONTROLLER://kafka3:29094,EXTERNAL://0.0.0.0:9094,BROKER://0.0.0.0:19094
      KAFKA_ADVERTISED_LISTENERS: CONTROLLER://kafka3:29094,EXTERNAL://${EXTERNAL_HOST}:9094, BROKER://kafka3:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT,BROKER:SASL_PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # SASL/PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas.conf

      # ACLs
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_SUPER_USERS: User:admin;User:broker

      # Replication
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./security/admin-client.properties:/etc/kafka/admin-client.properties
      - kafka3-data:/var/lib/kafka/data
      - ./security/jaas.conf:/etc/kafka/jaas.conf
    restart: always

networks:
  kraft-net:
    name: kafka-kraft-network

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data: